---
- hosts: linux
  tasks:
    # Deploy Apache on RedHat-based hosts like Fedora
    - block:
        - dnf: name=httpd state=present
        - template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
        - service: name=httpd state=started enabled=yes
      when: ansible_os_family == 'RedHat'
      become: yes
      become_method: sudo

      rescue:
      - name: run if error in this block
        debug: msg="Failed to deploy Apache"

    # Deploy Apache on Debian-based hosts like Ubuntu
    - block:
         - apt: name=apache2 state=present
         - template: src=apache2.conf dest=/etc/apache2/apache2.conf
         - service: name=apache2 state=started enabled=yes
      when: ansible_os_family == 'Debian'
      become: yes
      become_method: sudo

